############ Thymeleaf Start ##################################
spring:
  thymeleaf:
    cache: false  #1.开发环境，关闭缓存，有利于测试
    mode: LEGACYHTML5 #2.用非严格的HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
##########  Thymeleaf end  #######################################
